/home/michael/Downloads/prm_2023_test/build/main.o: main.cpp \
 /home/michael/Downloads/prm_2023_test/include/ReadAmberData.h \
 /usr/local/src/root_v5.34-36/include/TROOT.h \
 /usr/local/src/root_v5.34-36/include/TDirectory.h \
 /usr/local/src/root_v5.34-36/include/TNamed.h \
 /usr/local/src/root_v5.34-36/include/TObject.h \
 /usr/local/src/root_v5.34-36/include/Rtypes.h \
 /usr/local/src/root_v5.34-36/include/RConfig.h \
 /usr/local/src/root_v5.34-36/include/RVersion.h \
 /usr/local/src/root_v5.34-36/include/DllImport.h \
 /usr/local/src/root_v5.34-36/include/Rtypeinfo.h \
 /usr/local/src/root_v5.34-36/include/snprintf.h \
 /usr/local/src/root_v5.34-36/include/strlcpy.h \
 /usr/local/src/root_v5.34-36/include/TGenericClassInfo.h \
 /usr/local/src/root_v5.34-36/include/TSchemaHelper.h \
 /usr/local/src/root_v5.34-36/include/TStorage.h \
 /usr/local/src/root_v5.34-36/include/TVersionCheck.h \
 /usr/local/src/root_v5.34-36/include/Riosfwd.h \
 /usr/local/src/root_v5.34-36/include/TBuffer.h \
 /usr/local/src/root_v5.34-36/include/TString.h \
 /usr/local/src/root_v5.34-36/include/TMathBase.h \
 /usr/local/src/root_v5.34-36/include/TList.h \
 /usr/local/src/root_v5.34-36/include/TSeqCollection.h \
 /usr/local/src/root_v5.34-36/include/TCollection.h \
 /usr/local/src/root_v5.34-36/include/TIterator.h \
 /usr/local/src/root_v5.34-36/include/TDatime.h \
 /usr/local/src/root_v5.34-36/include/TUUID.h \
 /home/michael/Downloads/prm_2023_test/include/ReadVmmData.h \
 /usr/local/src/root_v5.34-36/include/TApplication.h \
 /usr/local/src/root_v5.34-36/include/TQObject.h \
 /usr/local/src/root_v5.34-36/include/TApplicationImp.h
